{Memory error and leak logging demo application.

When deploying this application, be sure to include the .map file generated by the linker, as well as the debug mode
support DLL: FastMM_FullDebugMode.dll (FastMM_FullDebugMode64.dll for 64-bit) in the same folder as the executable.}

program LogLeaksAndErrorsToFile;

{$APPTYPE CONSOLE}

{$R *.res}

uses
  FastMM5,
  System.SysUtils;

procedure ConfigureFastMM;
begin
  {Puts FastMM in debug mode.  In order to obtain stack traces for leaks and errors you need to do the following:
  1) Enable a detailed map file in Project Options under Linking -> Map File
  2) Put the FastMM_FullDebugMode.dll (FastMM_FullDebugMode64.dll for 64-bit) in the same folder as the executable.
  3) Either put the .map file in the same folder as the executable OR embed JCL debug info into the executable.}
  FastMM_EnterDebugMode;

  {We do not want any dialog boxes for errors or leaks.}
  FastMM_MessageBoxEvents := [];

  {We want all errors, memory leak details as well as leak summaries logged to a text file.}
  FastMM_LogToFileEvents := FastMM_LogToFileEvents + [mmetUnexpectedMemoryLeakDetail, mmetUnexpectedMemoryLeakSummary];
end;

procedure LeakMemory;
begin
  TObject.Create;
end;

begin
  ConfigureFastMM;

  LeakMemory;
end.
